version: '3'
services:
    db:
        image: postgres
        container_name: "pg-container"
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=imoveis_db
        ports:
            - "5432:5432"
        volumes:
            - "./db:/var/lib/postgresql/data/"